spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/moida?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8&allowPublicKeyRetrieval=true}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

cors:
  allowed-origins:
    - http://localhost:5173

logging:
  level:
    com.moida: debug
